project_id = "rycxacqyrgxpuckvqrag"

[functions.plr-analyzer]
verify_jwt = true

[functions.batch-editor]
verify_jwt = true

[functions.content-spinner]
verify_jwt = true

[functions.file-converter]
verify_jwt = true

[functions.html-editor]
verify_jwt = true

[functions.license-verifier]
verify_jwt = false

[functions.ocr-tool]
verify_jwt = true

[functions.seo-analyzer]
verify_jwt = true

[functions.translator]
verify_jwt = true

[functions.uniqueness-meter]
verify_jwt = true
